name: /data/huyvt/zaloai2022/ZaloAIChallenge-2022/env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2022.10.11=h06a4308_0
  - certifi=2022.9.24=py39h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.3=h5eee18b_3
  - openssl=1.1.1s=h7f8727e_0
  - pip=22.2.2=py39h06a4308_0
  - python=3.9.13=haa1d7c7_2
  - readline=8.2=h5eee18b_0
  - setuptools=65.5.0=py39h06a4308_0
  - sqlite=3.39.3=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - tzdata=2022f=h04d1e81_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.6=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - absl-py==1.3.0
    - aiohttp==3.8.3
    - aiosignal==1.2.0
    - albumentations==1.3.0
    - alembic==1.8.1
    - antlr4-python3-runtime==4.8
    - anyio==3.6.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.1.0
    - async-timeout==4.0.2
    - attrs==22.1.0
    - autopage==0.5.1
    - babel==2.11.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - black==22.10.0
    - bleach==5.0.1
    - cachetools==5.2.0
    - cffi==1.15.1
    - cfgv==3.3.1
    - charset-normalizer==2.1.1
    - click==8.1.3
    - cliff==4.0.0
    - cmaes==0.8.2
    - cmd2==2.4.2
    - colorama==0.4.6
    - colorlog==6.7.0
    - commonmark==0.9.1
    - contourpy==1.0.6
    - cycler==0.11.0
    - debugpy==1.6.3
    - decorator==5.1.1
    - defusedxml==0.7.1
    - distlib==0.3.6
    - docker-pycreds==0.4.0
    - entrypoints==0.4
    - executing==1.2.0
    - fastjsonschema==2.16.2
    - filelock==3.8.0
    - flake8==5.0.4
    - fonttools==4.38.0
    - frozenlist==1.3.1
    - fsspec==2022.10.0
    - gitdb==4.0.9
    - gitpython==3.1.29
    - google-auth==2.14.0
    - google-auth-oauthlib==0.4.6
    - greenlet==2.0.0.post0
    - grpcio==1.50.0
    - huggingface-hub==0.10.1
    - hydra-colorlog==1.1.0
    - hydra-core==1.1.0
    - hydra-optuna-sweeper==1.1.0
    - identify==2.5.8
    - idna==3.4
    - imageio==2.22.4
    - importlib-metadata==5.0.0
    - ipykernel==6.17.0
    - ipython==8.6.0
    - ipython-genutils==0.2.0
    - isort==5.10.1
    - jedi==0.18.1
    - jinja2==3.1.2
    - joblib==1.2.0
    - json5==0.9.10
    - jsonschema==4.17.0
    - jupyter-client==7.4.4
    - jupyter-core==4.11.2
    - jupyter-server==1.21.0
    - jupyter-server-mathjax==0.2.6
    - jupyterlab==3.5.0
    - jupyterlab-git==0.39.3
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.16.2
    - kiwisolver==1.4.4
    - lpips==0.1.4
    - mako==1.2.3
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.6.2
    - matplotlib-inline==0.1.6
    - mccabe==0.7.0
    - mistune==2.0.4
    - multidict==6.0.2
    - mypy-extensions==0.4.3
    - nbclassic==0.4.8
    - nbclient==0.7.0
    - nbconvert==7.2.3
    - nbdime==3.1.1
    - nbformat==5.7.0
    - nest-asyncio==1.5.6
    - networkx==2.8.8
    - nodeenv==1.7.0
    - notebook==6.5.2
    - notebook-shim==0.2.2
    - numpy==1.19.5
    - oauthlib==3.2.2
    - omegaconf==2.1.2
    - opencv-python==4.6.0.66
    - opencv-python-headless==4.6.0.66
    - optuna==2.4.0
    - packaging==21.3
    - pandas==1.4.4
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathspec==0.10.1
    - pathtools==0.1.2
    - pbr==5.11.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.3.0
    - platformdirs==2.5.3
    - pre-commit==2.20.0
    - prettytable==3.5.0
    - prometheus-client==0.15.0
    - promise==2.3
    - prompt-toolkit==3.0.32
    - protobuf==3.19.6
    - psutil==5.9.3
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.9.1
    - pycparser==2.21
    - pydeprecate==0.3.2
    - pyflakes==2.5.0
    - pygments==2.13.0
    - pyparsing==3.0.9
    - pyperclip==1.8.2
    - pyrsistent==0.19.2
    - python-dateutil==2.8.2
    - pytorch-lightning==1.7.7
    - pytz==2022.6
    - pywavelets==1.4.1
    - pyyaml==6.0
    - pyzmq==24.0.1
    - qudida==0.0.4
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rich==12.6.0
    - rsa==4.9
    - scikit-image==0.19.3
    - scikit-learn==1.1.3
    - scipy==1.9.3
    - seaborn==0.12.1
    - send2trash==1.8.0
    - sentry-sdk==1.10.1
    - setproctitle==1.3.2
    - shortuuid==1.0.9
    - six==1.16.0
    - smmap==5.0.0
    - sniffio==1.3.0
    - soupsieve==2.3.2.post1
    - sqlalchemy==1.4.43
    - stack-data==0.6.0
    - stevedore==4.1.0
    - tensorboard==2.10.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - terminado==0.17.0
    - threadpoolctl==3.1.0
    - tifffile==2022.10.10
    - timm==0.6.11
    - tinycss2==1.2.1
    - toml==0.10.2
    - tomli==2.0.1
    - torch==1.12.1+cu116
    - torch-fidelity==0.3.0
    - torchmetrics==0.10.2
    - torchvision==0.13.1+cu116
    - tornado==6.2
    - tqdm==4.64.1
    - traitlets==5.5.0
    - typing-extensions==4.4.0
    - urllib3==1.26.12
    - virtualenv==20.16.6
    - wandb==0.13.5
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.4.2
    - werkzeug==2.2.2
    - yarl==1.8.1
    - zipp==3.10.0
prefix: /data/huyvt/zaloai2022/ZaloAIChallenge-2022/env
